### PR TITLE
Add and fix Aqua tests

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR adds [Aqua](https://github.com/JuliaTesting/Aqua.jl) tests, specifically, `Aqua.test_unbound_args(ClimaCore)`, which tests that no functions defined in ClimaCore run into [this julia issue](https://github.com/JuliaLang/julia/issues/29393).

Adding this test revealed 9 instances of this issue, and the PR also includes fixes so that we pass all of the tests.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
It may be that we want to include type parameters in `copyto!`, in which case, the only solution I see is to split the method based on the unions of the input arguments to ensure that we don't run into this problem.

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try-

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
I think this is ready to go, cc @simonbyrne. Going to squash now.

**Comment by charleskawczynski** [comment]
All these changes look safe to me. Merging. cc @simonbyrne.

**Comment by simonbyrne** [comment]
Thanks!

**Pull request merged**
