### PR TITLE
Bubble modifications

### PR DESCRIPTION
**Pull request by akshaysridhar**
Interpolation b.c. -> Extrapolate
Coarser resolution
Collect upwind flux correction terms
Add plot outputs 
Separate kappa_4 and kappa_2 for hypervisc / second order visc
	modified:   bubble.jl

### CODE REVIEW

**Comment by szy21** [comment]
LGTM, thanks! I'm not sure if we want both diffusion and hyperdiffusion though? Are there any plots of the results somewhere?

**Comment by akshaysridhar** [comment]
https://user-images.githubusercontent.com/43710045/141146048-1b6a8d7f-fd2b-459d-b7a6-b76e48c30417.mp4
mass
energy

**Review by szy21 — APPROVED** [review]
Thanks @akshaysridhar! Please feel free to squash, rebase, and merge.

**Comment by akshaysridhar** [comment]
bors try

**Comment by akshaysridhar** [comment]
bors try

**Pull request merged**
