### PR TITLE
add custom release notes to tagbot

### PR DESCRIPTION
**Pull request by jakebolewski**
remove the previous attempt as it conflicted with the default Tagbot action

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]
Wow! This automates the release notes?!

**Comment by jakebolewski** [comment]
It's Jninja, which is a bit python centric

**Comment by jakebolewski** [comment]
Looks like I missed a typo :-/

https://github.com/CliMA/ClimaCore.jl/pull/291/files#diff-866b91571452393003c033893fb5d59671eb878db016d8d7c58f6b96b8c015daR43

**Comment by charleskawczynski** [comment]
Ah, dang, sorry, I missed that too

**Pull request merged**
