### PR TITLE
Fix reference to global variable

### PR DESCRIPTION
**Pull request by charleskawczynski**
It looks like this may happen in many examples, I'll apply to others, I just want to see what CI looks like with these changes, first.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Review by valeriabarra — APPROVED** [review]

**Comment by simonbyrne** [comment]
@charleskawczynski what's happening with this?

**Comment by charleskawczynski** [comment]
I need to apply this fix to more examples. I'll try to come back around on it tomorrow.

**Comment by jakebolewski** [comment]
Again, I would focus in on a 2 representative examples (a 3D sphere case and a 3D LES case).  The model we need to be fast is not the dycore example projects but the atmos model.  Things will get lost in translation so we need only a good baseline perf. indicator(s) to do measurements on.

**Comment by charleskawczynski** [comment]
Okay, I didn't get to this the other day, and I agree about where to focus efforts, but I'd still like to update this just to mitigate the spread of bad patterns.

**Comment by szy21** [comment]
Just want to add to the discussion if you are not sure which examples to focus on:

Explicit:
```
examples/hybrid/bubble3d_invariant_totalenergy.jl
examples/3dsphere/baroclinic_wave.jl
```

Implicit (still waiting for the correction in the implicit solver):
```
examples/3dsphere/baroclinic_wave_rho_etot.jl
examples/3dsphere/held_suarez_rho_etot.jl
```

**Comment by charleskawczynski** [comment]
This was basically superseded by #493. I'll reopen after adding perf analysis to held suarez and the 3d hybrid bubble

**Pull request closed without merging**
