### PR TITLE
update dependencies, remove CUDA_PATH var

### PR DESCRIPTION
**Pull request by simonbyrne**
This fixes bug in CUDA_Runtime_Discovery.jl

- [ ] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code is exercised in an integration test OR N/A.
- [ ] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by simonbyrne** [comment]
@charleskawczynski the benchmarks are failing: I think we need to rethink this approach.

**Comment by charleskawczynski** [comment]
@simonbyrne, is it okay to just increase the buffer?

**Comment by charleskawczynski** [comment]
@simonbyrne, I think it'll stagnate after we update it a few times. I know it's not perfect, but I'm not sure there is a perfect way to do this to ensure we catch if performance does degrade

**Pull request merged**
