### PR TITLE
Finite difference operators to use vectors 

### PR DESCRIPTION
**Pull request by jakebolewski**

### CODE REVIEW

**Comment by jakebolewski** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
Fun: https://buildkite.com/clima/climacore-ci/builds/183#73896f51-3ec9-4099-a226-3217264ed813/96-102

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
Looks like pinning `TriangularSolve.jl` to 0.1.5 and unpinning `RecursiveFactorizaitons.jl` resolved the segfault, I think this is ready to be squashed and merged.

**Pull request merged**
