### PR TITLE
Bump version, update dependencies

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR bumps the ClimaCore patch version and updates the dependencies.

### CODE REVIEW

**Comment by simonbyrne** [comment]
That might make a breaking change though?

**Comment by charleskawczynski** [comment]
I can try to remove the `Device` module first, the functions in the `Device` module exist in ClimaComms?

**Comment by simonbyrne** [comment]
yes, i believe so

**Comment by simonbyrne** [comment]
we could just import them for now, and move them to a deprecated file

**Comment by charleskawczynski** [comment]
> > I can try to remove the Device module first, the functions in the Device module exist in ClimaComms?

> yes, i believe so

Let me see what doing that looks like.

**Comment by valeriabarra** [comment]
Is the plan to update ClimaCore in ClimaAtmos then right after this? 
I was going to tag a ClimaAtmos release soon, but I can wait until we update ClimaCore to `0.10.33` in Atmos before tagging ClimaAtmos `v0.11.0`

**Comment by charleskawczynski** [comment]
> Is the plan to update ClimaCore in ClimaAtmos then right after this? I was going to tag a ClimaAtmos release soon, but I can wait until we update ClimaCore to `0.10.33` in Atmos before tagging ClimaAtmos `v0.11.0`

It may take some time to tag a new ClimaCore release (this may depend on #1215), I suggest not waiting. We can always tag another one so that we are able to do more incremental updates.

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
@simonbyrne, looks like this is ready!

**Comment by simonbyrne** [comment]
Did you bump ClimaCoreTempestRemap?

**Comment by charleskawczynski** [comment]
> Did you bump ClimaCoreTempestRemap?

Ah, right, the ClimaCoreTempestRemap patch version?

**Comment by charleskawczynski** [comment]
Done!

**Comment by charleskawczynski** [comment]
cc @simonbyrne

**Comment by valeriabarra** [comment]
Hey @charleskawczynski , can we just wait for #1219 to merge-in first? It should be passing tests. That way we can tag the release with the bug fix :pray:

**Comment by charleskawczynski** [comment]
> Hey @charleskawczynski , can we just wait for #1219 to merge-in first? It should be passing tests. That way we can tag the release with the bug fix 🙏

I think we can merge them together

**Pull request merged**
