### PR TITLE
Define copyto! for diagonalized field vectors

### PR DESCRIPTION
**Pull request by charleskawczynski**
Based on some analysis, we're hoping this improves performance a bit. cc @simonbyrne

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Review by simonbyrne — COMMENTED** [review]
Why not add it to src?

**Comment by charleskawczynski** [comment]
@simonbyrne, @szy21, @jiahe23, @dennisYatunin, it looks like the performance for our implicit cases are improved with this PR:

```
                                                   |  main   | this PR
examples/3dsphere/baroclinic_wave_rho_etot.jl      | 23m 23s | 10m 18s
examples/3dsphere/baroclinic_wave_rho_theta.jl     | 23m 57s | 10m 21s
examples/3dsphere/held_suarez_rho_etot.jl          | 24m 21s | 12m 11s
examples/3dsphere/held_suarez_rho_theta.jl         | 26m 14s | 10m 30s
```

Also, allocations go from 968.233 GiB to 7.197 GiB. 🎉

**Comment by charleskawczynski** [comment]
> Why not add it to src?

Oh, whoops 😆, I thought I did.

**Comment by charleskawczynski** [comment]
Well, now I'm curious if any other cases might improve from this.

**Comment by charleskawczynski** [comment]
bors try

**Review by simonbyrne — APPROVED** [review]

**Comment by charleskawczynski** [comment]
Ok, maybe it'll be helpful to look at Rising bubble 2D hybrid in the same way, since that one still allocates 1TB (which is _very_ strange for a 2D case).

**Comment by charleskawczynski** [comment]
Related issue: #275

**Pull request merged**
