### PR TITLE
Diffusion of total enthalpy in tendency terms

### PR DESCRIPTION
**Pull request by akshaysridhar**
Modifies examples to include total enthalpy hyperdiffusion in the tendency terms for 
\rhoe_tot. Resolves issue #552

### CODE REVIEW

**Review by szy21 — APPROVED** [review]
Looks good to me, thanks! Please squash, rebase, and bors r+.

**Comment by akshaysridhar** [comment]
bors try

**Comment by akshaysridhar** [comment]
bors try

**Comment by akshaysridhar** [comment]
bors try

**Comment by akshaysridhar** [comment]
bors try

**Comment by akshaysridhar** [comment]
bors try

**Comment by akshaysridhar** [comment]
@szy21 The rhoe held_suarez test breaks at the current `dt` with hyperdiffusion on total enthalpy ; reducing `dt` for this driver. Simulation end (10 day) norm is now 
```
[ Info: L₂ norm of ρe at t = 864000.0: 20115.683766516744
```

**Comment by akshaysridhar** [comment]
bors try

**Comment by szy21** [comment]
> @szy21 The rhoe held_suarez test breaks at the current `dt` with hyperdiffusion on total enthalpy ; I'm now reducing `dt` for this driver in this PR. Simulation end (10 day) norm is now
> 
> ```
> [ Info: L₂ norm of ρe at t = 864000.0: 20115.683766516744
> ```

Sounds good, thanks! Now rhoe and rhotheta have the same dt, which probably makes sense:)

**Pull request merged**
