### PR TITLE
Update BandedMatrices

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR:
 - Updates the BandedMatrices compat
 - Updates the manifest files

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
The buildkite failures are suspicious, going to retry

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try-

**Pull request merged**
