### PR TITLE
Support dss for Covariant123Vector

### PR DESCRIPTION
**Pull request by sriharshakandala**
Provide support for DSS of Covariant123Vector

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by sriharshakandala** [comment]
bors try

**Comment by sriharshakandala** [comment]
bors try-

**Comment by sriharshakandala** [comment]
bors try

**Comment by simonbyrne** [comment]
Can you add a test?

**Comment by simonbyrne** [comment]
A quick note as to why this is valid: our metric terms are computed from the partial derivative matrix
```math
\frac{\partial x}{\partial \xi} =
\begin{bmatrix}
H & 0 \\
(\nabla_h z)^\top & \Delta_v z
\end{bmatrix}
```
where 
- $H = \frac{\partial x_h }{\partial \xi_{1,2}}$ is the horizontal derivative matrix, which may be different at colocated points.
- $(\nabla_h z)^\top = \frac{\partial z}{\partial \xi_{1,2}}$ is the horizontal gradient of $z$ across levels. This has been DSS-ed (with respect to the horizontal metric terms), which means that ${H^{-1}}^\top \nabla_h z$ are the same at colocated points.
- $\Delta_v z$ is the vertical gradient of $z$: since all points in the same column are colocated, this should also be the same at colocated points.

This means that when we do the conversion to $(u,v,w)$:
```math
\begin{bmatrix}
u \\ v \\ w
\end{bmatrix}
=
\left(\frac{\partial \xi}{\partial x}\right)^\top
\begin{bmatrix}
u_1 \\ u_2 \\ u_3
\end{bmatrix}
=
\begin{bmatrix}
{H^{-1}}^\top & 
\frac{{H^{-1}}^\top \nabla_h z}{\Delta_v z} \\
0 & \frac{1}{\Delta_v z}
\end{bmatrix}
\begin{bmatrix}
u_h \\ u_3
\end{bmatrix}
```
the coefficients of the $u_3$ term will be the same at all colocated points.

Similarly, we have the inverse map
```math
\begin{bmatrix}
u_h \\ u_3
\end{bmatrix}
=
\left(\frac{\partial x}{\partial \xi}\right)^\top
\begin{bmatrix}
u \\ v \\ w
\end{bmatrix}
=
\begin{bmatrix}
H^\top & \nabla_h z \\
0 & \Delta_v z
\end{bmatrix}
\begin{bmatrix}
u \\ v \\ w
\end{bmatrix}
```

First consider just $u_3$: if $u_3^{(i)}$ are the colocated points we're DSS-ing, and $W^{(i))}$ are the normalized weights the DSS-ed values $\hat{u}^{(i)}_3$ are
```math
\hat{u}^{(i)}_3 
= (\Delta_v z) \sum_j W^{(j)} \frac{1}{(\Delta_v z)} u^{(j)}_3
=  \sum_j w^{(j)} u^{(j)}_3
```
since $(\Delta_v z)$ is the same at all colocated points.

Similarly for $u_h = (u_1, u_2)$, let $Q = \frac{{H^{-1}}^\top \nabla_h z}{\Delta_v z}$ (which as noted above, is the same at all colocated points), then
```math
\hat u_h^{(i)}
=  H^\top \sum_j W^{(j)} \left([(H^{-1})^\top u_h]^{(j)} +  Q u_3^{(j)} \right) + (\Delta_v z) \sum_j W^{(j)} \frac{1}{(\Delta_v z)} u^{(j)}_3
```
which I'm pretty sure cancels out to just the horizontal terms (to be continued...)

**Comment by sriharshakandala** [comment]
bors try

**Comment by sriharshakandala** [comment]
bors try

**Comment by sriharshakandala** [comment]
bors try

**Comment by sriharshakandala** [comment]
bors try

**Review by simonbyrne — APPROVED** [review]

**Pull request merged**
