### PR TITLE
Upwind3rdOrderBiasedProductC2F and simple FCT: Add varying sign veloc…

### LINKED ISSUE #873: Add unit test to test 3rd-order-upwinding with varying sign velocity
**Is your feature request related to a problem? Please describe.**
Currently, our unit test for the `Upwind3rdOrderBiasedProdctC2F` uses a constant and always positive velocity. 

**Describe the solution you'd like**
We could add a test with a varying sign velocity (e.g., a cosine profile) and test this, at least in the simple, periodic mesh case.

### PR DESCRIPTION
**Pull request by valeriabarra**
…ity unit tests

This was requested in the review of #872 

This will close #873 
I think it's expected that we see some degraded convergence rate. I think I remember Tapio mentioned this when this operator was discussed a while ago.

I added unit tests with varying sign velocity for the periodic mesh case and non-periodic mesh cases with `ThirdOrderOneSided` BC. The other one (`FirstOrderOneSided`) is already not accurate enough and also Tapio suggested we should favor using the `ThirdOrderOneSided` for this reason.

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by valeriabarra** [comment]
bors try

**Comment by valeriabarra** [comment]
Exact solution
exact
Vs computed
adv
for the stretched, non-periodic mesh case with `ThirdOrderOneSided`

Looking good

**Review by charleskawczynski — APPROVED** [review]
Thanks for adding this! LGTM

**Pull request merged**
