### PR TITLE
Bump version for new release

### PR DESCRIPTION
**Pull request by charleskawczynski**

### CODE REVIEW

**Comment by simonbyrne** [comment]
Can you bump the version (and ClimaCore requirement) of ClimaCoreVTK?

**Comment by jakebolewski** [comment]
I think it would be good to also update the release note logic to just use the built-in Tagbot one, let me issue a quick PR for that.

**Comment by jakebolewski** [comment]
https://github.com/CliMA/ClimaCore.jl/pull/291

**Review by jakebolewski — APPROVED** [review]

**Pull request merged**
