### PR TITLE
Plane limiters example: reverse flow

### PR DESCRIPTION
**Pull request by valeriabarra**
This small PR updates the plane limiters example to have a more similar flow to the spherical case (i.e., a flow that is reversed halfway through the period).

### CODE REVIEW

**Comment by valeriabarra** [comment]
https://user-images.githubusercontent.com/39932030/163898676-2e85d549-aa46-4e9a-87a7-c01ec3e48a17.mp4

**Comment by valeriabarra** [comment]
https://user-images.githubusercontent.com/39932030/164086842-fc520ad4-5597-4b89-8642-083d9301da33.mp4

**Comment by valeriabarra** [comment]
bors try

**Comment by valeriabarra** [comment]
Gaussian bells test case
https://user-images.githubusercontent.com/39932030/164117589-e05f3259-7b68-487a-b310-88a0601301a2.mp4

@simonbyrne , perhaps those lines that I noticed earlier in this test case are more visible. What do you think?

**Comment by valeriabarra** [comment]
Cosine bells test case 

https://user-images.githubusercontent.com/39932030/164118726-3f1c97dc-1a2c-47f2-bd37-445c6769f7c3.mp4

**Comment by valeriabarra** [comment]
@simonbyrne I replotted these test cases using vtk and indeed, I cannot see those lines. So I think we should be safe to say that they were indeed a visualization interpolation artifact. 

Cylinders test case in vtk output:
https://user-images.githubusercontent.com/39932030/165191543-a9e050a4-de23-4dab-8460-577527bff796.mp4

Cosine bells test case in vtk output:
 

https://user-images.githubusercontent.com/39932030/165191584-4eaffe9c-82ff-4f42-a2f9-de71f9d09d2c.mp4

**Comment by valeriabarra** [comment]
Now my only concern is the error that has risen (see latest buildkite run on `main`, e.g. this [one](https://buildkite.com/clima/climacore-ci/builds/984#b64a95d0-3fa9-4fb6-bf31-c6dde13ff1ce/99)) compared to this buildkite job. Why do you think that could be?

**Comment by valeriabarra** [comment]
> Now my only concern is the error that has risen (see latest buildkite run on `main`, e.g. this [one](https://buildkite.com/clima/climacore-ci/builds/984#b64a95d0-3fa9-4fb6-bf31-c6dde13ff1ce/99)) compared to this buildkite job. Why do you think that could be?

I also tried halving the time step, but it didn't get better, it actually got worse, which is quite puzzling. See this sample run:

```
julia> include("examples/plane/limiters_advection.jl")
[ Info: Test case: cylinders
[ Info: With limiter: true
[ Info: Hyperdiffusion coefficient: D₄ = 0.0
[ Info: Number of elements in domain: 32 x 32
[ Info: Number of quadrature points per element: 4 x 4 (p = 3)
[ Info: Time step dt = 0.0005 (s)
[ Info: ("Tracer concentration norm at t = 0 (s): ", 0.3970195356890555)
[ Info: ("Tracer concentration norm at 12566 time steps, t = 6.283185307179586 (s): ", 0.37412620635701344)
[ Info: ("L₁ error at 12566 time steps, t = 6.283185307179586 (s): ", 0.1710242750608533)
[ Info: ("L₂ error at 12566 time steps, t = 6.283185307179586 (s): ", 0.7000183316888394)
[ Info: ("L∞ error at 12566 time steps, t = 6.283185307179586 (s): ", 7.363388663048914)
```

**Comment by valeriabarra** [comment]
@simonbyrne this PR is ready for review. I'd like this to be merged soon so that I can address #687  and #610 asap. Thanks

**Review by simonbyrne — APPROVED** [review]

**Pull request merged**
