### PR TITLE
Add ntuple field perf tests

### PR DESCRIPTION
**Pull request by charleskawczynski**

### CODE REVIEW

**Review by jakebolewski — APPROVED** [review]

**Comment by jakebolewski** [comment]
Have you checked with an optimization test if we can infer these large tuples correctly?

**Comment by charleskawczynski** [comment]
> Have you checked with an optimization test if we can infer these large tuples correctly?

Yeah, JET says everything is inferrable, but we're still somehow incurring allocations. What we had to do in ClimateMachine was propagate indexes down via `Val`. It looks like this could be affecting the non-FD stencils, too

**Comment by charleskawczynski** [comment]
Hmm, that was when I commented everything else out aside from the new test. Need to take a second look

**Comment by charleskawczynski** [comment]
Ah, I redefined a field, which had the same effect as redefining operators. Everything looks good.

**Pull request merged**
