### PR TITLE
Add lim+FCT run to deformation flow example

### PR DESCRIPTION
**Pull request by valeriabarra**
This PR adds the combination of limiters and FCT as an additional run to the deformation flow example. So far these two contributions were tested separately. 

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by valeriabarra** [comment]
bors try

**Comment by valeriabarra** [comment]
This test still ran in 13 min, even with the added combination and related artifacts. So I think it's good to add

**Review by charleskawczynski — APPROVED** [review]

**Pull request merged**
