### PR TITLE
Use ClimaTimeSteppers in implicit hydro balance example

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR changes the implicit hydro balance example to use ClimaTimeSteppers.

This is a peel off from https://github.com/CliMA/ClimaCore.jl/pull/1358.

This will technically have behavior changes because we're switching from `Rosenbrock23` to `ARS343`

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
This is actually breaking (we're using `soft_fail` on this job)

**Comment by charleskawczynski** [comment]
bors try

**Comment by dennisYatunin** [comment]
Oh, sorry, I was looking at the ClimaAtmos code. In this file, it would be `Wfact = jacobian!`. The `jac = jacobian!` is not used by ClimaTimeSteppers (because the thing we're actually specifying here is `I - dt * gamma * J`, rather than `J` itself).

**Comment by dennisYatunin** [comment]
Actually, looking more closely at this, I don't think that will work. The `jacobian!(J, Y, p, t)` function needs to be rewritten as a `Wfact!(W, Y, p, dtγ, t)` function (so `J` needs to be replaced with `I - dtγ * J`), and then `linsolve!` needs to be modified to solve `A * x = b`, where `A = I - dtγ * J`, instead of whatever it's solving now.

**Comment by charleskawczynski** [comment]
Superseded by #1400

**Pull request closed without merging**
