### PR TITLE
isothermal channel example

### PR DESCRIPTION
**Pull request by akshaysridhar**
Linked Issue #1100 

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Review by Zhengyu-Huang — APPROVED** [review]
Thanks for the great work, it looks good for me!

**Comment by akshaysridhar** [comment]
bors try

**Comment by akshaysridhar** [comment]
Added this to buildkite + bors try is successful ; @simonbyrne can I merge this ? We can iterate on this (or produce a similar example within ClimaAtmos if this is helpful with the PR1234 tests)

**Review by simonbyrne — APPROVED** [review]
Yes let's merge this

**Pull request merged**
