### PR TITLE
Use ReportMetrics.jl

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR changes our `perf/allocs.jl` to use ReportMetrics.jl, which helps remove a bit of boiler plate, as this is used in several other repos.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Review by jakebolewski — APPROVED** [review]

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by simonbyrne** [comment]
Very nice!

BTW, you can add links in buildkite output, if you wanted to link the line to the source code:
https://buildkite.com/docs/pipelines/links-and-images-in-log-output

**Comment by jakebolewski** [comment]
There is a stub there for linking to github source code line in buildkite output, I think we found a general way to make it work for most all registered packages in the project.

**Pull request merged**
