### PR TITLE
Update CUDA and dependencies

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR updates the CUDA compat entry and the dependencies, upgrading us to CUDA 5.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Review by Sbozzolo — APPROVED** [review]
Just leaving this here for our reference:

> 
> CUDA.jl 5.0 raises the required Julia and CUDA versions. The minimum Julia version is now 1.8, which should be enforced by the Julia package manager. The minimum CUDA toolkit version is now 11.4, but this cannot be enforced by the package manager. As a result, if you need to use an older version of the CUDA toolkit, you will need to pin CUDA.jl to v4.4 or below. [The README](https://github.com/JuliaGPU/CUDA.jl/blob/master/README.md) now contains a table of supported CUDA toolkit versions and the corresponding CUDA.jl release.
> 
> Most users will not be affected by this change: If you use the artifact-provided CUDA toolkit, you will automatically get the latest version supported by your CUDA driver.

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by simonbyrne** [comment]
It doesn't look like we're using CUDA 5: do you know what's blocking the upgrade?

**Comment by charleskawczynski** [comment]
> It doesn't look like we're using CUDA 5: do you know what's blocking the upgrade?

Oh, weird, I thought it was, let me check.

**Comment by charleskawczynski** [comment]
@simonbyrne, alright, manifests were updated. I'll run CI to see how this goes.

**Comment by charleskawczynski** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try-

**Comment by simonbyrne** [comment]
bors try

**Pull request merged**
