### PR TITLE
Pin to ubuntu-20.04

### PR DESCRIPTION
**Pull request by sriharshakandala**
Pin Ubuntu version to ubuntu-20.04 in github workflows

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Review by charleskawczynski — COMMENTED** [review]
I guess this is okay if @simonbyrne is alright with removing this. This just provides a visual. Should we open an issue about getting this working again? Also, this doesn't affect coverage at all, correct?

**Comment by sriharshakandala** [comment]
> Details

Yes. All  `ClimaCoreVTK` tests are passing.

**Comment by sriharshakandala** [comment]
> I guess this is okay if @simonbyrne is alright with removing this. This just provides a visual. Should we open an issue about getting this working again? Also, this doesn't affect coverage at all, correct?

Yes. All  `ClimaCoreVTK` tests are passing.

**Comment by simonbyrne** [comment]
Yes, please open an issue

**Review by charleskawczynski — APPROVED** [review]

**Pull request merged**
