### PR TITLE
Add implicit Baroclinic wave

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR is a rebased branch from #414, which has only the necessary pieces to run the implicit baroclinic wave, and adds it to CI.

Credit to many others in getting thi working, I merely pushed it past the finish line at the last moment.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by szy21** [comment]
bors try

**Comment by szy21** [comment]
Note: need to change rhs after #440

**Pull request merged**
