### PR TITLE
Fix WeightedIntepolate operators

### PR DESCRIPTION
**Pull request by simonbyrne**
We were erroneously dividing by 2. It turns out these weren't being tested by the convergence tests.

cc @Zhengyu-Huang @akshaysridhar 

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by Zhengyu-Huang** [comment]
@akshaysridhar  you mentioned there might be `2` issue  in the boundary treatment?

**Comment by simonbyrne** [comment]
> @akshaysridhar you mentioned there might be `2` issue in the boundary treatment?

I think the boundary handling should be the same as the unweighted operators. I've updated the docs.

**Comment by simonbyrne** [comment]
bors try

**Comment by akshaysridhar** [comment]
> > @akshaysridhar you mentioned there might be `2` issue in the boundary treatment?
> 
> I think the boundary handling should be the same as the unweighted operators. I've updated the docs.

Yes, I looked over this and I agree !

**Review by akshaysridhar — APPROVED** [review]

**Comment by akshaysridhar** [comment]
bors try

**Review by Zhengyu-Huang — APPROVED** [review]
Thank you for the great work! Please merge it ASAP!

**Pull request merged**
