### PR TITLE
remove test compat

### PR DESCRIPTION
**Pull request by simonbyrne**
See if we can remove these

Alternative to #911

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]

**Comment by simonbyrne** [comment]
I'll merge this so we can unblock stuff, and deal with the 1.8 breakages in another PR.

**Comment by simonbyrne** [comment]
@charleskawczynski perf tests are failing!

**Pull request merged**
