### PR TITLE
Examples & docs Manifest : use ClimaCore v0.10.1

### PR DESCRIPTION
**Pull request by valeriabarra**
- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by valeriabarra** [comment]
bors try

**Comment by simonbyrne** [comment]
can you also update the `docs` one as well?

**Comment by valeriabarra** [comment]
> can you also update the `docs` one as well?

Done

**Pull request merged**
