### PR TITLE
fix energy equations

### PR DESCRIPTION
**Pull request by szy21**
Add the missing pressure term in the energy equations.

### CODE REVIEW

**Comment by szy21** [comment]
bors try

**Comment by szy21** [comment]
bors try-

**Comment by jiahe23** [comment]
same here
https://github.com/CliMA/ClimaCore.jl/blob/main/examples/3dsphere/solid_body_rotation_3d.jl#L188-L190

**Comment by szy21** [comment]
bors try

**Review by jiahe23 — APPROVED** [review]

**Pull request merged**
