### PR TITLE
Add invalidations script

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR adds a script for monitoring invalidations, so that we can incrementally fix egregious method invalidations (which can lead to slow compile times).

### CODE REVIEW

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
https://buildkite.com/clima/climacore-ci/builds/1540#0183f71b-f860-4eaa-a93e-0fd1b3bc48a8/148-153

**Comment by charleskawczynski** [comment]
whoops, meant to try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
Invalidations table (see in build [here](https://buildkite.com/clima/climacore-ci/builds/1543#0183f772-74e9-4d3d-b40a-7c950d014e22/141-167)):

```
[ Info: Number of invalidations for invalidations: 5933
[ Info: invalidations: 117 total method invalidations (showing 10)
┌──────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────┬───────────────┬─────────────────┐
│ <file name>:<line number>                                                                    │     Method Name     │ Invalidations │ Invalidations % │
│                                                                                              │                     │    Number     │     (xᵢ/∑x)     │
├──────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────┼───────────────┼─────────────────┤
│ /central/scratch/esm/slurm-buildkite/climacore-ci/1543/climacore-ci/src/Fields/Fields.jl:438 │        show         │     2697      │       35        │
│ FileIO/aP78L/src/types.jl:136                                                                │        write        │     1327      │       17        │
│ Plots/AAjgN/src/backends/hdf5.jl:582                                                         │ _initialize_subplot │      802      │       10        │
│ Static/pkxBE/src/bool.jl:32                                                                  │          !          │      372      │        5        │
│ ArrayInterface/TCj9U/src/ranges.jl:239                                                       │        Colon        │      313      │        4        │
│ Static/pkxBE/src/int.jl:26                                                                   │       Integer       │      289      │        4        │
│ BlockArrays/B2UXn/src/blockbroadcast.jl:223                                                  │     instantiate     │      212      │        3        │
│ ProgressLogging/6KXlp/src/ProgressLogging.jl:211                                             │       convert       │      188      │        2        │
│ Static/pkxBE/src/bool.jl:113                                                                 │    promote_rule     │      167      │        2        │
│ ProgressLogging/6KXlp/src/ProgressLogging.jl:216                                             │         cmp         │      147      │        2        │
└──────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┴───────────────┴─────────────────┘
```

**Pull request merged**
