### PR TITLE
add Float32 support to driver

### LINKED ISSUE #621: Check whether the examples run with Float32

### PR DESCRIPTION
**Pull request by simonbyrne**
Fixes #621

### CODE REVIEW

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
@szy21 it looks like there is a minor performance advantage (516 seconds vs 609 seconds for held suarez) for Float32

**Comment by szy21** [comment]
Thanks!

**Pull request merged**
