### PR TITLE
Use DSS2 in SpectralElementSpace2D

### PR DESCRIPTION
**Pull request by sriharshakandala**
- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by sriharshakandala** [comment]
bors try

**Comment by sriharshakandala** [comment]
bors try

**Comment by sriharshakandala** [comment]
bors try

**Comment by simonbyrne** [comment]
Can we simply redefine `weighted_dss!` to be `weighted_dss2!`?

**Comment by sriharshakandala** [comment]
> Can we simply redefine `weighted_dss!` to be `weighted_dss2!`?

I believe so, for backward compatibility. I user interfaces are designed to be identical. I am adding dss2 support for `ContravariantVector`, which is needed by a few tests.

**Comment by sriharshakandala** [comment]
bors try

**Comment by sriharshakandala** [comment]
bors try

**Comment by sriharshakandala** [comment]
bors try

**Comment by sriharshakandala** [comment]
bors try

**Comment by sriharshakandala** [comment]
bors try

**Comment by sriharshakandala** [comment]
bors try

**Comment by sriharshakandala** [comment]
bors try

**Pull request merged**
