### PR TITLE
test IO on GPU

### PR DESCRIPTION
**Pull request by simonbyrne**
Add tests for IO with CUDA-backed fields.

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by sriharshakandala** [comment]
Can we please add the IO test to the GPU/CUDA test suite?

**Comment by simonbyrne** [comment]
We automatically run all the tests on the GPU: I've just modified the test files so that they will use the GPU if it is set.

**Comment by sriharshakandala** [comment]
bors try

**Comment by simonbyrne** [comment]
@sriharshakandala any more comments?

**Comment by sriharshakandala** [comment]
> @sriharshakandala any more comments?

Looks good to me. Can we  add a quick word in the test descriptor to print the device it is running on?

**Review by sriharshakandala — APPROVED** [review]

**Pull request merged**
