### PR TITLE
add docs for ClimaCore libs

### PR DESCRIPTION
**Pull request by simonbyrne**

### CODE REVIEW

**Comment by jakebolewski** [comment]
maybe it would be a good time to move the build to the cluster

**Comment by simonbyrne** [comment]
> maybe it would be a good time to move the build to the cluster

I think it's fine for now: if we add more tutorials we can re-evaluate.

**Comment by simonbyrne** [comment]
Since moving the plots, the graphics aren't rendering in the tutorial. I tried adding `using ClimaCorePlots`, but that didn't seem to fix it.

**Comment by simonbyrne** [comment]
oh it's not running at all!

**Comment by jakebolewski** [comment]
I've also noticed in the past that nothing is highlighted correctly :-/

**Comment by simonbyrne** [comment]
okay, the tutorial hadn't been running since we changed some of the vector stuff

I've hopefully fixed that, and enabled strict mode on the example blocks, so hopefully should be okay now

**Comment by jakebolewski** [comment]
awesome, looks much better. I'll add the docs for the plotting / makie stuff to get started in another PR

**Review by jakebolewski — APPROVED** [review]

**Pull request merged**
