### PR TITLE
Add rossby haurwitz wave test case

### PR DESCRIPTION
**Pull request by szy21**
Open the PR for the record. We can talk about where to put the test case in the end.

### CODE REVIEW

**Comment by valeriabarra** [comment]
bors try

**Comment by valeriabarra** [comment]
bors try-

**Comment by valeriabarra** [comment]
bors try

**Comment by valeriabarra** [comment]
This is ready on my end and the artifacts look good to me. 
@szy21 if happy, we can squash commits as you like

**Review by simonbyrne — APPROVED** [review]

**Comment by szy21** [comment]
Looks good to me, thanks! @valeriabarra Would you like to squash it?

**Comment by valeriabarra** [comment]
Done

**Pull request merged**
