### PR TITLE
a few IO tweaks

### PR DESCRIPTION
**Pull request by simonbyrne**
- Add version number to file
- Use `eval` from `ClimaCore` module

- [ ] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code is exercised in an integration test OR N/A.
- [ ] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by sriharshakandala** [comment]
The PR looks good to me, but it is not clearing the tests yet!

**Comment by simonbyrne** [comment]
Okay, I refactored a bit to clean up a bit: it splits out the functions and caches for loading different types of objects, and makes the handling of FieldVectors a bit more flexible

**Comment by simonbyrne** [comment]
@sriharshakandala okay, tests should be passing now

**Review by sriharshakandala — APPROVED** [review]

**Pull request merged**
