### PR TITLE
Add support for GPUs in interpolate_array

### PR DESCRIPTION
**Pull request by Sbozzolo**

### CODE REVIEW

**Comment by Sbozzolo** [comment]
bors try

**Comment by Sbozzolo** [comment]
bors try

**Comment by Sbozzolo** [comment]
bors try

**Comment by Sbozzolo** [comment]
bors try

**Comment by Sbozzolo** [comment]
bors try

**Comment by Sbozzolo** [comment]
bors try

**Comment by Sbozzolo** [comment]
bors try

**Comment by Sbozzolo** [comment]
bors try

**Comment by Sbozzolo** [comment]
bors try

**Comment by Sbozzolo** [comment]
bors try

**Comment by Sbozzolo** [comment]
bors try

**Comment by Sbozzolo** [comment]
One of the tests is failing. I probably didn't push the last version, let me look into this.

**Comment by simonbyrne** [comment]
CI error:
https://buildkite.com/clima/climacore-ci/builds/2810#018bba97-8b98-4b0c-b3a9-0c845258ed44/165-169

**Comment by Sbozzolo** [comment]
I think I did some `git mess up`, and now I to recover the correct version.

**Comment by Sbozzolo** [comment]
Found missing commit

**Comment by Sbozzolo** [comment]
CI is green, @simonbyrne, if you want to review.

**Review by simonbyrne — APPROVED** [review]

**Pull request merged**
