### PR TITLE
time unit tests

### PR DESCRIPTION
**Pull request by simonbyrne**
Try to figure out why we're getting timeouts.

UPDATE: I've moved the long-running test (30 mins) to a separate buildkite job

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]
Looks fine to me. I assume both we're using `-O0` due to long compilation times?

**Comment by simonbyrne** [comment]
> Looks fine to me. I assume both we're using `-O0` due to long compilation times?

yeah, it cut down the time by quite a lot.

**Pull request merged**
