### PR TITLE
Bump compat for CubedSphere to 0.3

### PR DESCRIPTION
**Pull request by Sbozzolo**
CubedSphere 0.3 does not introduce any new feature, it moves some accessory features out of the package. In this, most dependencies are dropped.

Now, ClimaCore no longer depends on FFTW and the various other dependencies that are pulled in with FFTW.

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]
Nice! I remembered there was a related issue with FFTW, but it turns out that this was in ClimateMachine (https://github.com/CliMA/ClimateMachine.jl/issues/1478). So, that's a nice dependency to remove.

**Comment by charleskawczynski** [comment]
Hm, the error is a bit odd. I'll try pushing a commit to update the manifests.

**Comment by charleskawczynski** [comment]
It looks like OrdinaryDiffEq broke into many subpackages? Maybe we can now adjust our dependencies on it in the test/examples environment.

**Comment by charleskawczynski** [comment]
Weird, the versions got downgraded During develop or instantiate. I’m gonna try clearing the depot.

**Comment by charleskawczynski** [comment]
Looks like we'll need to update this, limit OrdinaryDiffEq, or figure out how to eliminate this dependency. @dennisYatunin, was `update_W!` part of the public API?

**Comment by Sbozzolo** [comment]
Many of the places where OrdindaryDiffEq is currently used should be changed with SciMLBase.

**Comment by charleskawczynski** [comment]
> Many of the places where OrdindaryDiffEq is currently used should be changed with SciMLBase.

Yeah, I tried removing it a while back, but we need some of the algorithms, which don't exist in SciMLBase. Maybe we can use the subpackages now that it's split

**Pull request merged**
