### PR TITLE
print output on error in TempestRemap

### LINKED ISSUE #727: ClimaCoreTempestRemap: print output if there is an error
**Is your feature request related to a problem? Please describe.**
We currently suppress output of TempestRemap wrappers, even if an error occurs
https://buildkite.com/clima/climaatmos-longruns/builds/114#cf5327d1-546b-437c-9905-cef9a08e4bfa/133-167

**Describe the solution you'd like**
Capture the output to an `IOBuffer`, then print it if the process fails.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by simonbyrne**
Fixes #727

cc @juliasloan25 

- [ ] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code is exercised in an integration test OR N/A.
- [ ] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]
Very nice improvement

**Comment by juliasloan25** [comment]
Thanks Simon!

**Pull request merged**
