### PR TITLE
Bump version, update news

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR bumps the patch version for a new release, and updates the news.

### CODE REVIEW

**Comment by Sbozzolo** [comment]
#2103 and #2060 are ready for review and it would be nice to have them in this release (unless you need the release urgently)

**Comment by charleskawczynski** [comment]
> #2103 and #2060 are ready for review and it would be nice to have them in this release (unless you need the release urgently)

I merged #2103. Maybe you can rebase #2060? @tapios wanted the recently added limiters to be the default by Monday, so maybe we can do a few releases?

**Comment by Sbozzolo** [comment]
> > #2103 and #2060 are ready for review and it would be nice to have them in this release (unless you need the release urgently)
> 
> I merged #2103. Maybe you can rebase #2060? @tapios wanted the recently added limiters to be the default by Monday, so maybe we can do a few releases?

I rebased (only the NEWS file had conflicts), but it's fine if the PR goes in at a later date.

**Comment by charleskawczynski** [comment]
> I rebased (only the NEWS file had conflicts), but it's fine if the PR goes in at a later date.

Thank you! I'll merge this, make a patch release, and prioritize reviewing #2060 so that we can get that through.

**Pull request merged**
