### PR TITLE
Widen OrdinaryDiffEq and SciMLBase compat range

### PR DESCRIPTION
**Pull request by charleskawczynski**
This is kind of a peel off from #1235. This PR widens the compat range for OrdinaryDiffEq and SciMLBase

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
This has gotten kind of big, and I have no idea why the IGW example is breaking, which worked on the previous commit.. I'll break this down.

**Comment by simonbyrne** [comment]
We can also just ditch OrdinaryDiffEq support for now if that is easier?

**Comment by charleskawczynski** [comment]
> We can also just ditch OrdinaryDiffEq support for now if that is easier?

I don't think that ditching it altogether is any easier than upgrading. This PR does have some things that we maybe don't need though, I'll rebase it after #1364 is merged and try to remove some of the unnecessary stuff.

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
I'm happy to merge this if we can merge #1400 first, cc @simonbyrne

**Comment by charleskawczynski** [comment]
The IGW problem needed a smaller dt. I'm going to bisect once or twice to preserve resources.

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Pull request merged**
