### PR TITLE
Customized tridiagonal solver

### PR DESCRIPTION
**Pull request by Zhengyu-Huang**
Tridiagonal solver
Can be optimized

### CODE REVIEW

**Comment by OsKnoth** [comment]
can we add also a version, for storing the factorization, or we should change to the Thomas algorithm,

**Comment by Zhengyu-Huang** [comment]
> can we add also a version, for storing the factorization, or we should change to the Thomas algorithm,

I do not know how to store the factorization, The tridiagonal solver uses Thomas algorithm

**Comment by bischtob** [comment]
bors try

**Comment by bischtob** [comment]
@Zhengyu-Huang , is this ready?

**Comment by jakebolewski** [comment]
This needs to get cleaned up before it is merged.

**Comment by Zhengyu-Huang** [comment]
> This needs to get cleaned up before it is merged, can you clean up the example a bit and rebase / squash the changes?

Hi Jake, I update it in the hydrostatic_implicit.jl

**Review by jakebolewski — APPROVED** [review]

**Pull request merged**
