### PR TITLE
option for deep atmosphere

### LINKED ISSUE #1524: Hypsography is not GPU-compatible
Creating a space with hypsography results in 
```
  Scalar indexing is disallowed.
  Invocation of getindex resulted in scalar indexing of a GPU array.
  This is typically caused by calling an iterating implementation of a method.
  Such implementations *do not* execute on the GPU, but very slowly on the CPU,
  and therefore are only permitted from the REPL for prototyping purposes.
  If you did intend to index this array, annotate the caller with @allowscalar.
  Stacktrace:
    [1] error(s::String)
      @ Base ./error.jl:35
    [2] assertscalar(op::String)
      @ GPUArraysCore ~/.julia/packages/GPUArraysCore/uOYfN/src/GPUArraysCore.jl:103
    [3] getindex(::CUDA.CuArray{Float64, 5, CUDA.Mem.DeviceBuffer}, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64)
      @ GPUArrays ~/.julia/packages/GPUArrays/EZkix/src/host/indexing.jl:9
    [4] getindex
      @ ./subarray.jl:286 [inlined]
    [5] _getindex
      @ ./abstractarray.jl:1346 [inlined]
    [6] getindex
      @ ./abstractarray.jl:1296 [inlined]
    [7] get_struct
      @ ~/ClimaCore.jl/src/DataLayouts/struct.jl:218 [inlined]
    [8] macro expansion
      @ ~/ClimaCore.jl/src/DataLayouts/struct.jl:200 [inlined]
    [9] macro expansion
      @ ./none:0 [inlined]
   [10] get_struct
      @ ./none:0 [inlined]
   [11] macro expansion
      @ ~/ClimaCore.jl/src/DataLayouts/struct.jl:200 [inlined]
   [12] macro expansion
      @ ./none:0 [inlined]
   [13] get_struct
      @ ./none:0 [inlined]
   [14] getindex
      @ ~/ClimaCore.jl/src/DataLayouts/DataLayouts.jl:949 [inlined]
   [15] ClimaCore.Spaces.ExtrudedFiniteDifferenceSpace(horizontal_space::ClimaCore.Spaces.maComms.CUDADevice}, ClimaCore.Meshes.RectilinearMesh{ClimaCore.Meshes.IntervalMesh{ClimaC.Geometry.XPoint{Float64}, Int64}}, ClimaCore.Meshes.IntervalMesh{ClimaCore.Domains.Intervloat64}, Int64}}}, CartesianIndices{2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}, LineaInt64, Int64, Bool}, 1, CUDA.Mem.DeviceBuffer}, Vector{Tuple{Int64, Int64, Int64, Int64, BCUDA.Mem.DeviceBuffer}, CUDA.CuArray{Tuple{Bool, Int64, Int64}, 1, CUDA.Mem.DeviceBuffer},{Int64, Int64}, 1, CUDA.Mem.DeviceBuffer}}, ClimaCore.Spaces.Quadratures.GLL{4}, ClimaCoretry{(1, 2), ClimaCore.Geometry.XYPoint{Float64}, Float64, StaticArraysCore.SMatrix{2, 2, FH{Float64, 4, CUDA.CuArray{Float64, 4, CUDA.Mem.DeviceBuffer}}, ClimaCore.DataLayouts.IFH{CuArray{Float64, 3, CUDA.Mem.DeviceBuffer}}, NamedTuple{(), Tuple{}}}, vertical_space::ClivalTopology{ClimaComms.SingletonCommsContext{ClimaComms.CUDADevice}, ClimaCore.Meshes.Inte Symbol}}, LinRange{ClimaCore.Geometry.ZPoint{Float64}, Int64}}, NamedTuple{(:bottom, :top.VF{ClimaCore.Geometry.LocalGeometry{(3,), ClimaCore.Geometry.ZPoint{Float64}, Float64, St}, adaption::ClimaCore.Hypsography.LinearAdaption{ClimaCore.Fields.Field{ClimaCore.DataLayectralElementSpace2D{ClimaCore.Topologies.Topology2D{ClimaComms.SingletonCommsContext{Clime.Domains.IntervalDomain{ClimaCore.Geometry.XPoint{Float64}, Nothing}, LinRange{ClimaCore.Domain{ClimaCore.Geometry.YPoint{Float64}, Nothing}, LinRange{ClimaCore.Geometry.YPoint{Flndices{2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}, CUDA.CuArray{Tuple{Int64, Int64, Il}}, CUDA.CuArray{Tuple{Int64, Int64}, 1, CUDA.Mem.DeviceBuffer}, CUDA.CuArray{Int64, 1, CUDA.CuArray{Int64, 1, CUDA.Mem.DeviceBuffer}, NamedTuple{(), Tuple{}}, CUDA.CuArray{Tuple{eometry.CartesianGlobalGeometry, ClimaCore.DataLayouts.IJFH{ClimaCore.Geometry.LocalGeometat64, 4}}, 4, CUDA.CuArray{Float64, 4, CUDA.Mem.DeviceBuffer}}, ClimaCore.DataLayouts.IJFHimaCore.Geometry.SurfaceGeometry{Float64, ClimaCore.Geometry.UVVector{Float64}}, 4, CUDA.C      @ ClimaCore.Hypsography ~/ClimaCore.jl/src/Hypsography/Hypsography.jl:141
```

### PR DESCRIPTION
**Pull request by simonbyrne**
Adds option to configure an extruded sphere with the metric terms for a deep atmosphere.

Part of https://github.com/CliMA/ClimaAtmos.jl/issues/2497

I think this should also fix #1524.

Todo
- [x] add tests: any ideas?
- [x] add topography support

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by simonbyrne** [comment]
I think this is ready to go, however it does change the hypsography interface slightly (surfaces are now fields of `ZPoint`s), so it should probably be a breaking change.

**Comment by Sbozzolo** [comment]
There are some incompatibilities with the (non-conservative) interpolation interface.

Here's some context:

The interpolation scheme has to work in the reference coordinates but accepts an interpolation grid both in reference and physical coordinates. When the interpolation grid is in physical coordinates, the coordiantes are transformed to reference. For this to happen, the interpolation functions have to know about the function that maps physical coordinates to reference ones (R2P). 

On the other side, we hypsography by providing a function that maps reference coordinates to physics (P2R). It happens that not all the coordinate transformations have a nice inverse function. Our current SLEVE is an example.
Our SLEVE looks like `zphys = zref + A sinh(B zref)`, which does not admit a closed form inverse. We do not want to solve nonlinear equations every time we interpolate.

The interpolation interface will have to be reworked, my proposal is to postpone the problem to the future.

I noticed that our current SLEVE can be represented rather faithfully by a LinearizedSLEVE.

Let's look at the details:

Our SLEVE is (for $\frac{z_{ref}}{z_{top}} < \eta_H$):

$$ z_{phys} = z_{ref} + \frac{1}{\sinh{1/s}} \sinh \left( \frac{\eta_H - z_{ref} / z_{top}}{s \eta_H}  \right) $$

Let's focus on the term in the sinh. By definition, we are considering the regime where the numerator is smaller than one, so the argument is always smaller than $1\ {s \eta_H}$. Now, typical values for $\eta_H$ are $(0.5, 0.8)$, and $s$ is order 10. Therefore, the argument of sinh is of order 0.1. We can approximate the $\sinh$ at the first order.

$$ z_{phys} = z_{ref} + \frac{1}{\sinh{1/s}} \left( \frac{\eta_H - z_{ref} / z_{top}}{s \eta_H}  \right) $$

This function is now linear and easily invertible. 

What's the truncation error? The truncation error gets smaller for increasing $\eta_H$, decreasing $z_{surf}$ and increasing $z_{top}$. For $s > 5$ and $\eta_H = 0.5$, the maximum relative error is 0.5 %, which is tiny! With $s = 2$, the maximum error grows to 3 %.
image

I have ideas on how to handle the most general case, but in the interest of merging this as soon as possible, I think we can just implement the `LinearizedSLEVE`.

**Comment by Sbozzolo** [comment]
Upon further inspection (and checking with @akshaysridhar), linearized SLEVE in this regime is pretty much our linear adaption.

**Comment by akshaysridhar** [comment]
There is currently a method overload for sums over `ZPoints`. This affects the diagnostic write step (see, for instance, the default diagnostic `orog` as shown below). The method overload is a workaround, but I don't think this is the consistent, long-term solution. To reproduce this error, trigger a new job with topography and default diagnostics enabled, such that the `Surface Altitude` diagnostic is written to disk - This results in the undef method error: 
```
julia --project=examples examples/hybrid/driver.jl --config config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M_earth.yml
[ Info: Running on CPUSingleThreaded.
[ Info: Setting up single-process ClimaAtmos run
[ Info: Running ClimaCore in unthreaded mode.
┌ Info: numerics
│            `energy_upwinding`::`Val{:none}`
│            `tracer_upwinding`::`Val{:none}`
│            `precip_upwinding`::`Val{:none}`
│             `edmfx_upwinding`::`Val{:none}`
│     `edmfx_sgsflux_upwinding`::`Val{:none}`
│     `test_dycore_consistency`::`Nothing`
│                     `limiter`::`Nothing`
└         `use_reference_state`::`Bool`
...
...
[ Info: NetCDFWriter: ["orog_inst", "ts_1d_average", "ta_1d_average", "thetaa_1d_average", "ha_1d_average", "pfull_1d_average", "rhoa_1d_average", "ua_1d_average", "va_1d_average", "wa_1d_average", "hfes_1d_average", "ts_1d_max", "ts_1d_min", "hur_1d_average", "hus_1d_average", "cl_1d_average", "clw_1d_average", "cli_1d_average", "hussfc_1d_average", "evspsbl_1d_average", "pr_1d_average", "rsd_1d_average", "rsu_1d_average", "rld_1d_average", "rlu_1d_average"]
[ Info: Prepared diagnostic callbacks: 945.583 ms (2805587 allocations: 202.86 MiB)
[ Info: Prepared SciMLBase.CallbackSet callbacks: 14.369 ms (411 allocations: 29.72 KiB)
[ Info: n_steps_per_cycle_per_cb (non diagnostics): [1, 1, 8640, 216, 108, 1]
[ Info: n_steps_per_cycle_per_cb_diagnostic: [1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864]
[ Info: n_steps_per_cycle (non diagnostics): 8640
[ Info: Define ode function: 4.449 s (13880282 allocations: 1.42 GiB)
[ Info: dt_save_to_sol: 86400.0, length(saveat): 1
[ Info: Saving state to HDF5 file on day 0 second 0
[ Info: init integrator: 158.753 s (54967531 allocations: 3.80 GiB)
ERROR: LoadError: Could not compute diagnostic Surface Altitude: MethodError(zero, (ClimaCore.Geometry.ZPoint{Float32},), 0x0000000000007bc3)
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] macro expansion
   @ ~/Codes/ClimaAtmos.jl/src/solver/type_getters.jl:963 [inlined]
 [3] macro expansion
   @ ./timing.jl:503 [inlined]
 [4] macro expansion
   @ ~/Codes/ClimaAtmos.jl/src/utils/utilities.jl:358 [inlined]
 [5] get_simulation(config::ClimaAtmos.AtmosConfig{Float32, CLIMAParameters.ParamDict{…}, Dict{…}, ClimaComms.SingletonCommsContext{…}})
   @ ClimaAtmos ~/Codes/ClimaAtmos.jl/src/solver/type_getters.jl:934
 [6] top-level scope
   @ ~/Codes/ClimaAtmos.jl/examples/hybrid/driver.jl:14
...

caused by: MethodError: no method matching zero(::Type{ClimaCore.Geometry.ZPoint{Float32}})

Closest candidates are:
  zero(::Type{Union{}}, Any...)
   @ Base number.jl:310
  zero(::Type{Dates.Time})
   @ Dates /clima/software/julia/julia-1.10.0/share/julia/stdlib/v1.10/Dates/src/types.jl:440
  zero(::Type{Pkg.Resolve.FieldValue})
   @ Pkg /clima/software/julia/julia-1.10.0/share/julia/stdlib/v1.10/Pkg/src/Resolve/fieldvalues.jl:38
  ...

Stacktrace:
 [1] zeros(::Type{ClimaCore.Geometry.ZPoint{Float32}}, dims::Tuple{Int64, Int64})
   @ Base ./array.jl:637
 [2] interpolate(remapper::ClimaCore.Remapping.Remapper{…}, field::ClimaCore.Fields.Field{…}; physical_z::Bool)
   @ ClimaCore.Remapping ~/Codes/ClimaCore.jl/src/Remapping/distributed_remapping.jl:241
 [3] write_field!(writer::ClimaAtmos.Diagnostics.NetCDFWriter{…}, field::ClimaCore.Fields.Field{…}, diagnostic::ClimaAtmos.Diagnostics.ScheduledDiagnosticIterations{…}, integrator::ClimaTimeSteppers.DistributedODEIntegrator{…}, output_dir::String)
   @ ClimaAtmos.Diagnostics ~/Codes/ClimaAtmos.jl/src/diagnostics/netcdf_writer.jl:630
 [4] macro expansion
   @ ~/Codes/ClimaAtmos.jl/src/solver/type_getters.jl:950 [inlined]
 [5] macro expansion
   @ ./timing.jl:503 [inlined]
 [6] macro expansion
   @ ~/Codes/ClimaAtmos.jl/src/utils/utilities.jl:358 [inlined]
 [7] get_simulation(config::ClimaAtmos.AtmosConfig{Float32, CLIMAParameters.ParamDict{…}, Dict{…}, ClimaComms.SingletonCommsContext{…}})
   @ ClimaAtmos ~/Codes/ClimaAtmos.jl/src/solver/type_getters.jl:934
 [8] top-level scope
   @ ~/Codes/ClimaAtmos.jl/examples/hybrid/driver.jl:14
--- Saving profiler information
```

**Comment by Sbozzolo** [comment]
> There is currently a method overload for sums / zeros over `ZPoints`. This affects the diagnostic write step (see, for instance, the default diagnostic `orog` as shown below). The method overload is a workaround (see `src/Remapping/distributed*` in this PR, but I don't think this is the consistent, long-term solution. To reproduce this error, trigger a new job with topography and default diagnostics enabled, such that the `Surface Altitude` diagnostic is written to disk - This results in the undef method error:
> 
> ```
> julia --project=examples examples/hybrid/driver.jl --config config/longrun_configs/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M_earth.yml
> [ Info: Running on CPUSingleThreaded.
> [ Info: Setting up single-process ClimaAtmos run
> [ Info: Running ClimaCore in unthreaded mode.
> ┌ Info: numerics
> │            `energy_upwinding`::`Val{:none}`
> │            `tracer_upwinding`::`Val{:none}`
> │            `precip_upwinding`::`Val{:none}`
> │             `edmfx_upwinding`::`Val{:none}`
> │     `edmfx_sgsflux_upwinding`::`Val{:none}`
> │     `test_dycore_consistency`::`Nothing`
> │                     `limiter`::`Nothing`
> └         `use_reference_state`::`Bool`
> ...
> ...
> [ Info: NetCDFWriter: ["orog_inst", "ts_1d_average", "ta_1d_average", "thetaa_1d_average", "ha_1d_average", "pfull_1d_average", "rhoa_1d_average", "ua_1d_average", "va_1d_average", "wa_1d_average", "hfes_1d_average", "ts_1d_max", "ts_1d_min", "hur_1d_average", "hus_1d_average", "cl_1d_average", "clw_1d_average", "cli_1d_average", "hussfc_1d_average", "evspsbl_1d_average", "pr_1d_average", "rsd_1d_average", "rsu_1d_average", "rld_1d_average", "rlu_1d_average"]
> [ Info: Prepared diagnostic callbacks: 945.583 ms (2805587 allocations: 202.86 MiB)
> [ Info: Prepared SciMLBase.CallbackSet callbacks: 14.369 ms (411 allocations: 29.72 KiB)
> [ Info: n_steps_per_cycle_per_cb (non diagnostics): [1, 1, 8640, 216, 108, 1]
> [ Info: n_steps_per_cycle_per_cb_diagnostic: [1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864, 1, 864]
> [ Info: n_steps_per_cycle (non diagnostics): 8640
> [ Info: Define ode function: 4.449 s (13880282 allocations: 1.42 GiB)
> [ Info: dt_save_to_sol: 86400.0, length(saveat): 1
> [ Info: Saving state to HDF5 file on day 0 second 0
> [ Info: init integrator: 158.753 s (54967531 allocations: 3.80 GiB)
> ERROR: LoadError: Could not compute diagnostic Surface Altitude: MethodError(zero, (ClimaCore.Geometry.ZPoint{Float32},), 0x0000000000007bc3)
> Stacktrace:
>  [1] error(s::String)
>    @ Base ./error.jl:35
>  [2] macro expansion
>    @ ~/Codes/ClimaAtmos.jl/src/solver/type_getters.jl:963 [inlined]
>  [3] macro expansion
>    @ ./timing.jl:503 [inlined]
>  [4] macro expansion
>    @ ~/Codes/ClimaAtmos.jl/src/utils/utilities.jl:358 [inlined]
>  [5] get_simulation(config::ClimaAtmos.AtmosConfig{Float32, CLIMAParameters.ParamDict{…}, Dict{…}, ClimaComms.SingletonCommsContext{…}})
>    @ ClimaAtmos ~/Codes/ClimaAtmos.jl/src/solver/type_getters.jl:934
>  [6] top-level scope
>    @ ~/Codes/ClimaAtmos.jl/examples/hybrid/driver.jl:14
> ...
> 
> caused by: MethodError: no method matching zero(::Type{ClimaCore.Geometry.ZPoint{Float32}})
> 
> Closest candidates are:
>   zero(::Type{Union{}}, Any...)
>    @ Base number.jl:310
>   zero(::Type{Dates.Time})
>    @ Dates /clima/software/julia/julia-1.10.0/share/julia/stdlib/v1.10/Dates/src/types.jl:440
>   zero(::Type{Pkg.Resolve.FieldValue})
>    @ Pkg /clima/software/julia/julia-1.10.0/share/julia/stdlib/v1.10/Pkg/src/Resolve/fieldvalues.jl:38
>   ...
> 
> Stacktrace:
>  [1] zeros(::Type{ClimaCore.Geometry.ZPoint{Float32}}, dims::Tuple{Int64, Int64})
>    @ Base ./array.jl:637
>  [2] interpolate(remapper::ClimaCore.Remapping.Remapper{…}, field::ClimaCore.Fields.Field{…}; physical_z::Bool)
>    @ ClimaCore.Remapping ~/Codes/ClimaCore.jl/src/Remapping/distributed_remapping.jl:241
>  [3] write_field!(writer::ClimaAtmos.Diagnostics.NetCDFWriter{…}, field::ClimaCore.Fields.Field{…}, diagnostic::ClimaAtmos.Diagnostics.ScheduledDiagnosticIterations{…}, integrator::ClimaTimeSteppers.DistributedODEIntegrator{…}, output_dir::String)
>    @ ClimaAtmos.Diagnostics ~/Codes/ClimaAtmos.jl/src/diagnostics/netcdf_writer.jl:630
>  [4] macro expansion
>    @ ~/Codes/ClimaAtmos.jl/src/solver/type_getters.jl:950 [inlined]
>  [5] macro expansion
>    @ ./timing.jl:503 [inlined]
>  [6] macro expansion
>    @ ~/Codes/ClimaAtmos.jl/src/utils/utilities.jl:358 [inlined]
>  [7] get_simulation(config::ClimaAtmos.AtmosConfig{Float32, CLIMAParameters.ParamDict{…}, Dict{…}, ClimaComms.SingletonCommsContext{…}})
>    @ ClimaAtmos ~/Codes/ClimaAtmos.jl/src/solver/type_getters.jl:934
>  [8] top-level scope
>    @ ~/Codes/ClimaAtmos.jl/examples/hybrid/driver.jl:14
> --- Saving profiler information
> ```

I started working on this. Working with `Field`s of `ZPoints` is more complex and I don't think the interpolation interface should handle that. Unfortunately, there's no trivial way to go from `ZPoint` to scalar, so I think the first step would be to add that. I know what to do and I'll open a PR very soon.

**Comment by akshaysridhar** [comment]
Superseded by #1606

**Pull request closed without merging**
