### PR TITLE
Add column example using Rosebrock implicit solver, extend broadcasting

### PR DESCRIPTION
**Pull request by simonbyrne**
This is currently failing due to ode_interpolate returning an object of the same type. For this to work properly, we need to make out-of-place broadcasting of `FieldVector`s work correctly.

### CODE REVIEW

**Comment by simonbyrne** [comment]
blocked by #120

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
@Zhengyu-Huang This might fix the issue: let me know.

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
@Zhengyu-Huang The timestepper appears to work, but it fails in the plots. If you can fix that, we can merge this in.

**Comment by bischtob** [comment]
bors try

**Review by bischtob — APPROVED** [review]
This is ready after inspection of simulation output by @Zhengyu-Huang.

**Pull request merged**
