### PR TITLE
Use better recursion pattern

### PR DESCRIPTION
**Pull request by charleskawczynski**
I'm hoping this was the big missing piece! 🤞🏻

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
Well, not as big performance improvement as I hoped, but it seems to be improving allocations quite a bit.

**Comment by jakebolewski** [comment]
Allocations are why we were using tuplemap and not map originally :).   Look like this one was missed, so it is good to have all cases covered now.

**Review by jakebolewski — APPROVED** [review]

**Pull request merged**
