### PR TITLE
fix agent implicit stencil gpu test

### PR DESCRIPTION
**Pull request by simonbyrne**
I wasn't requesting gpus correctly

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]

**Comment by charleskawczynski** [comment]
😕

**Comment by simonbyrne** [comment]
I actually think it might be the GPU code caching?

**Pull request merged**
