### PR TITLE
Add a FD perf test

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR adds a (broken) allocation test to the FD opt examples test suite. I'll see if I can Cthulhu in to find what's going wrong but may need help. cc @jakebolewski.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Looks like all we needed was to not limit recursion on `axes_args`.

**Comment by jakebolewski** [comment]
Is this just another form of https://github.com/CliMA/ClimaCore.jl/issues/346?

**Comment by charleskawczynski** [comment]
> Is this just another form of #346?

I don't think so, because AFAICT, this is the same as what's done in `alloc_test_operators_in_loops`, which "redefines" operators inside a loop.

**Comment by jakebolewski** [comment]
https://github.com/CliMA/ClimaCore.jl/pull/408/files#diff-ee589bf4d9c0274df366b1b03a2116d98c8ef9e6689c94f25cda1240d3fbbe79R486?

**Comment by charleskawczynski** [comment]
> https://github.com/CliMA/ClimaCore.jl/pull/408/files#diff-ee589bf4d9c0274df366b1b03a2116d98c8ef9e6689c94f25cda1240d3fbbe79R486?

Ahhhh, maybe that's it. I'll try changing that

**Review by jakebolewski — APPROVED** [review]

**Comment by jakebolewski** [comment]
The determining cause of this after going through it with @charleskawczynski is that the expression is too complex for the optimizer when combining the broadcasted expression axes (`Base.Broadcast.combine_axes()` in `_axes`).  We will have to probably re-write combine_axes carefully to prevent this from happening over a given complexity limit in the expression (number of recursive broadcast calls in the call tree) which will be a bit of work.  A workaround is to break up the above expression roughly in two (adding in the second expression) which doesn't trigger any allocations (hack but it is an easy heuristic to follow in model code for the time being).

**Pull request merged**
