### PR TITLE
inline all FD operators and axisvector conversions

### LINKED ISSUE #1455: Inline all the things
**Is your feature request related to a problem? Please describe.**
Function calls on GPUs are expensive, so it is important to inline as much as possible. Often see 10x performance difference on individual kernels.

There are 2 ways:
- make sure that every function we call is marked with either `@inline` or `@propagate_inbounds`
- use `@cuda always_inline=true`

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by simonbyrne**
Fixes #1455 

- [ ] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code is exercised in an integration test OR N/A.
- [ ] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by simonbyrne** [comment]
The GPU MatrixFields tests are running out of memory:
```
├ seff 37043560
Job ID: 37043560
Cluster: central
User/Group: spjbyrne/citstaff
State: COMPLETED (exit code 0)
Cores: 1
CPU Utilized: 00:36:46
CPU Efficiency: 99.19% of 00:37:04 core-walltime
Job Wall-clock time: 00:37:04
Memory Utilized: 80.15 GB
Memory Efficiency: 100.19% of 80.00 GB
```

**Comment by charleskawczynski** [comment]
I assume that this is blowing up codegen? 80GB is kind a lot

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
MatrixField failures are due to a memory leak. Will have to fix that elsewhere.

**Comment by charleskawczynski** [comment]
> MatrixField failures are due to a memory leak. Will have to fix that elsewhere.

Can you elaborate? Is it on our side? Or is it a Jjulia memory leak?

**Comment by simonbyrne** [comment]
I think there's a memory leak in the GPU compiler somewhere? @vchuravy any ideas?

**Pull request merged**
