### PR TITLE
add GlobalGeometry object for converting to Cartesian

### PR DESCRIPTION
**Pull request by simonbyrne**
Also updates the VTK interface to allow writing vector fields, as well as struct or other composite data.

### CODE REVIEW

**Comment by simonbyrne** [comment]
vectorfield
We can make nice pictures of vector fields

**Comment by simonbyrne** [comment]
@kpamnany I've updated the interface for `writevtk`

**Comment by kpamnany** [comment]
LGTM!

**Comment by sriharshakandala** [comment]
Looks good to me.

**Pull request merged**
