### PR TITLE
Add and fix broken tests for domain-point broadcasting

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR adds and fixes (most) broken tests for domain-surface broadcasting.

I don't think julia has something like `@test_broken_throws`, so my work-around is to use `@test_broken` with `try-catch`

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Alright, I think I fixed a bunch of the tests, I'm not sure if this is optimal, but it looks like it may be the right way. The only case that I didn't fix is the "PlanarSpace" and "3D" space (i.e., we have full functionality inside `bycolumn` loops now, because `PointSpace`s broadcast nicely with everything)

**Comment by charleskawczynski** [comment]
I apparently need one more fix:

```julia
@inline Base.Broadcast.broadcast_shape(
    pointspace::AbstractPointSpace,
    space::AbstractPointSpace,
) = space
@inline Base.Broadcast.broadcast_shape(
    space::AbstractPointSpace,
    pointspace::AbstractPointSpace,
) = space
```
is needed to avoid a method ambiguity. I'll see if I can make the test slightly more complicated to account for this case.

**Comment by charleskawczynski** [comment]
I just tried this out locally in ClimaAtmos, and it's working

**Comment by charleskawczynski** [comment]
@kmdeck, @braghiere , I imagine this may help fix missing support for the land model

**Comment by kmdeck** [comment]
thanks @charleskawczynski! Ill have time to take a closer look early next week.

**Review by simonbyrne — APPROVED** [review]

**Comment by simonbyrne** [comment]
https://buildkite.com/clima/climacore-ci/builds/1480#01836bbb-bd85-4fa3-a2b9-85850879899a/131-139

**Pull request merged**
