### PR TITLE
Add column plots

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR adds column plots to Held Suarez so that we can monitor the BCs over time.

Waiting on #626.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors ping

**Comment by charleskawczynski** [comment]
bors try

**Review by simonbyrne — APPROVED** [review]

**Comment by charleskawczynski** [comment]
Going to change variance to standard deviation, and try to change to using physical velocities

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
Ok, @simonbyrne, I think this is doing the right thing now, can you take a look?

**Comment by charleskawczynski** [comment]
bors try

**Pull request merged**
