### PR TITLE
Add ClimaCoreMakie to examples Project and Manifest

### PR DESCRIPTION
**Pull request by valeriabarra**
This is needed for this week's ClimaWorkshop to be able to have a reproducible environment for people to run examples and test the ClimaCoreMakie support

### CODE REVIEW

**Comment by jakebolewski** [comment]
The reason I was hesitant to add these as normal dependencies in the package itself and in the examples is that each require specific system libraries to be installed correctly on Linux (outside of BinaryBuilder deps).  This is probably not an issue on OSX and Win where the OpenGL driver stack is already installed.   I don't know how you want to handle this but that was the original rationale.

**Comment by valeriabarra** [comment]
> The reason I was hesitant to add these as normal dependencies in the package itself and in the examples is that each require specific system libraries to be installed correctly on Linux (outside of BinaryBuilder deps). This is probably not an issue on OSX and Win where the OpenGL driver stack is already installed. I don't know how you want to handle this but that was the original rationale.

Thanks for explaining.

**Comment by valeriabarra** [comment]
@simonbyrne it seems like as is, there would be a circular dependency issue. How do we want to solve this for the workshop?

**Comment by simonbyrne** [comment]
Unfortunately it looks like GLMakie won't work on the cluster. For the workshop it is probably best to use a separate Project.toml file.

**Pull request closed without merging**
