### PR TITLE
Conditionally overload Krylov.ktypeof

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR conditionally overloads `Krylov.ktypeof` using Requires. This is added here to avoid type piracy in ClimaAtmos. Alternatively to this PR, we could wait until we upgrade to Julia 1.9 and use package extensions.

### CODE REVIEW

**Review by simonbyrne — APPROVED** [review]
This seems reasonable. Once we switch to 1.9 we can use extensions.

**Comment by charleskawczynski** [comment]
Ah, I need to update the manifests since this PR adds the `Requires` dependency.

**Pull request merged**
