### PR TITLE
Diagonalize isapprox

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR diagonalize `isapprox`

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
Is this easier for the compiler?

**Comment by charleskawczynski** [comment]
At the very least, type diagonalizarion will yield better errors in isapprox.

**Comment by simonbyrne** [comment]
wait, did we resolve the issue with views?

**Comment by charleskawczynski** [comment]
> wait, did we resolve the issue with views?

Yeah, I reverted adding the type hint on delta, which is where we had the errors with the views

**Pull request merged**
