### PR TITLE
Warped mesh test case (single-peak)

### PR DESCRIPTION
**Pull request by akshaysridhar**
Collapses changes from `dh/warped-mesh` in PR#263 and `main` -> towards test cases with topography in a 2D box. 
Adds new test file: `advection_agnesi_mountain.jl` 
cc @Zhengyu-Huang @jakebolewski  @simonbyrne @szy21

### CODE REVIEW

**Comment by akshaysridhar** [comment]
@jakebolewski Before I rebase this can you please look over the modified files to make sure changes have been consistently brought over from the closed #263 PR ? Thanks!

**Comment by jakebolewski** [comment]
@akshaysridhar at this point it might make more sense to start piece-wise merging in the functionality if it looks reasonable and adding unit-tests.  I can work on that if it would be useful.  We will also need to generalize the impl for 3D product domains.

**Comment by jakebolewski** [comment]
that will make things a bit easier I think at this point (and easier to review)

**Comment by akshaysridhar** [comment]
> 

Thanks Jake, agreed, piecewise merge with unit-tests and splitting functionality (e.g. splitting warping / grid-stretching would he helpful at this stage).

**Comment by jakebolewski** [comment]
Ok I'll work on merging in the grid stretching first so we can tag a version for EDMF dev.

**Pull request closed without merging**
