### PR TITLE
add invalidations test

### PR DESCRIPTION
**Pull request by simonbyrne**
Adds a new GitHub workflow that checks for invalidations when loading

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]
Nice! This looks great, the test here is only that invalidations don't increase, right? Also, should we make bors depend on this?

**Comment by simonbyrne** [comment]
Yeah, I just copied this directly from MPI.jl, where it was added in https://github.com/JuliaParallel/MPI.jl/pull/622.

That PR linked to this discussion: https://discourse.julialang.org/t/potential-performance-regressions-in-julia-1-8-for-special-un-precompiled-type-dispatches-and-how-to-fix-them/86359

**Comment by simonbyrne** [comment]
Lets try it out for a week or so, then if it is reliable we can add it to bors.

**Pull request merged**
