### PR TITLE
Update threadblock configuration for SE kernels

### PR DESCRIPTION
**Pull request by sriharshakandala**
Update threadblock configuration for SE kernels, make necessary changes.
Explore storing Differentiation matrix in shared memory inside SE kernels.

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by sriharshakandala** [comment]
bors try

**Comment by sriharshakandala** [comment]
hdiv_current_Screenshot 2023-08-21 at 2 36 40 PM

**Comment by sriharshakandala** [comment]
hdiv_current_Screenshot 2023-08-21 at 2 36 40 PM
hdiv2_Screenshot 2023-08-21 at 2 35 40 PM

**Comment by simonbyrne** [comment]
This seems to work, and nests as I would hope.

One problem is that i'm seeing an odd slow down for functions applied _after_ an operator
```
julia> CUDA.@time @. Y = divₕ(rho * uₕ);
  0.001691 seconds (99 CPU allocations: 12.406 KiB)

julia> CUDA.@time @. Y = -divₕ(rho * uₕ);
  0.026079 seconds (111 CPU allocations: 14.828 KiB)
```

Need to look into it more.

**Comment by simonbyrne** [comment]
I suspect this we could be missing inlining somewhere (I saw a similar performance regression earlier when I missed some)

**Comment by simonbyrne** [comment]
This splits the `apply_kernel_operator` across 3 functions:
- `operator_shmem`: allocates the required shared memory for the operator
  - called by `allocate_shmem`, which reconstructs the expression tree where the `SpectralBroadcasted` objects fill in the `work` array with a `CuStaticSharedArray`
- `operator_fill_shmem!` fills in the shmem work array with the input values to the operator
  - called by `resolve_operator!`
- `operator_evaluate` evaluates the operator from the inputs stored in shmem
  - called by `getnode`

**Comment by sriharshakandala** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Review by simonbyrne — APPROVED** [review]

**Comment by sriharshakandala** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Review by charleskawczynski — COMMENTED** [review]
Can we add this benchmark to buildkite?

**Pull request merged**
