### PR TITLE
Use Nsight 2023.1.1

### PR DESCRIPTION
**Pull request by sriharshakandala**
Use Nsight 2023.1.1

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by sriharshakandala** [comment]
bors try

**Comment by simonbyrne** [comment]
Address an error. see https://github.com/CliMA/ClimaAtmos.jl/pull/1879

**Comment by simonbyrne** [comment]
Fixed in slurm-buildkite.

**Pull request closed without merging**
