### PR TITLE
Unpin HDF5_jll in test, update deps

### PR DESCRIPTION
**Pull request by Sbozzolo**
Fixing the `prrte_jll` woes.

### CODE REVIEW

**Comment by Sbozzolo** [comment]
bors try

**Comment by simonbyrne** [comment]
Looks like the perf is still stuck on the old HDF5, due to https://github.com/JuliaPackaging/Yggdrasil/issues/7531

**Comment by Sbozzolo** [comment]
bors try

**Comment by Sbozzolo** [comment]
bors try

**Comment by Sbozzolo** [comment]
bors try

**Comment by simonbyrne** [comment]
Closing in favor of #1543

**Pull request closed without merging**
