### PR TITLE
Dont use .style for FieldVectorStyle

### PR DESCRIPTION
**Pull request by charleskawczynski**
I think this should fix the failure in #1657.

### CODE REVIEW

**Comment by Sbozzolo** [comment]
Do you know why this is failing only in 1.9?

**Comment by charleskawczynski** [comment]
> Do you know why this is failing only in 1.9?

`style` must be an internal field, that was added in 1.10. There was always an associated style type, but perhaps not a field.

**Review by Sbozzolo — APPROVED** [review]
Thank you!

**Comment by Sbozzolo** [comment]
You can also add an entry in the NEWS if you feel like

**Pull request merged**
