### PR TITLE
Add Julia 1.10rc1 to GHA CI

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR adds Julia 1.10rc1 to GHA CI.

### CODE REVIEW

**Comment by simonbyrne** [comment]
GFlops.jl is broken on 1.10 (https://github.com/triscale-innov/GFlops.jl/issues/49)

**Comment by charleskawczynski** [comment]
bummer

**Comment by Sbozzolo** [comment]
I am going to make the Julia 1.10 test not a required check to merge PRs

**Comment by simonbyrne** [comment]
> I am going to make the Julia 1.10 test not a required check to merge PRs
> 
> EDIT: I cannot do it because it is the same workflow as 1.9 :/

Wait how did this merge then?

**Pull request merged**
