### PR TITLE
Always inline

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR makes all cuda kernel launches always inline, since this can reduce function call overhead. In addition, it could allow the compiler to hoist memory reads/writes.

### CODE REVIEW

**Comment by Sbozzolo** [comment]
I'd be good to check that this doesn't break coupler and land too.

**Comment by charleskawczynski** [comment]
Agreed, there’s still one thing to fix in atmos

**Comment by charleskawczynski** [comment]
Atmos is fixed.

**Comment by charleskawczynski** [comment]
I'm going to merge this, and we can fix the issues we run into.

**Comment by Sbozzolo** [comment]
> I'm going to merge this, and we can fix the issues we run into.

I am [rebuilding](https://buildkite.com/clima/climaland-ci/builds/3633) your PR in Land that tests this out.

**Pull request merged**
