### PR TITLE
Add profiling.

### PR DESCRIPTION
**Pull request by sriharshakandala**
Add Nsight profiling for distributed simulations.

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [ ] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by sriharshakandala** [comment]
bors try

**Comment by simonbyrne** [comment]
Do you mind if we leave this open for a bit? I think we want to register NVTX first.

**Comment by sriharshakandala** [comment]
> NVTX.jl has now been registered: can you switch to using the registered version?

Done.

**Comment by sriharshakandala** [comment]
bors try

**Comment by charleskawczynski** [comment]
This looks like a pretty invasive application of monitoring, can't we just apply this to `OrdinaryDiffEq.step!`? Or will `NVTX` not provide sufficient granularity?

**Comment by sriharshakandala** [comment]
> This looks like a pretty invasive application of monitoring, can't we just apply this to `OrdinaryDiffEq.step!`? Or will `NVTX` not provide sufficient granularity? Or is there some other reason / issue?

One objective was to measure the relative time being spent in the DSS portions of the code per timestep, which is what we did here.
I did try to expose the step of the ODE solver, but it was very entangled. Also, given that we will be moving to CliMATimesteppers anyways, I did not think it was worth the effort at this point.

**Pull request closed without merging**
