### PR TITLE
change vertex element ordering to counter-clockwise

### LINKED ISSUE #219: Use counter-clockwise ordering of vertices
Needs to update `vertex_coordinates` and bilinear interpolation to be consistent across all mesh types.

### PR DESCRIPTION
**Pull request by simonbyrne**
Fixes #219.

### CODE REVIEW

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
indeed. it does look like something is going wrong...

**Comment by sriharshakandala** [comment]
We need to update the documentation for the Mesh2D struct in Meshes.jl.
Screen Shot 2021-10-05 at 1 59 38 PM

is typical, but if we choose to use a different, we still need to update the documentation.

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try-

**Comment by simonbyrne** [comment]
bors try

**Pull request merged**
