### PR TITLE
add GPU support to bubble example

### PR DESCRIPTION
**Pull request by simonbyrne**
Makes it a bit easier to run and test

### CODE REVIEW

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by sriharshakandala** [comment]
bors try

**Pull request merged**
