### PR TITLE
Copyright caltech

### PR DESCRIPTION
**Pull request by simonbyrne**
CliMA isn't an org that can hold copyright, so it should be Caltech.

### CODE REVIEW

**Review by valeriabarra — APPROVED** [review]

**Comment by simonbyrne** [comment]
Maybe we should paste the whole license in?:
https://www.apache.org/licenses/LICENSE-2.0.txt

**Comment by simonbyrne** [comment]
Reading the actual license, it looked like we were applying it incorrectly. I have updated it accordingly.

**Pull request merged**
