### PR TITLE
add level interface function

### PR DESCRIPTION
**Pull request by simonbyrne**
It's a bit of a kludge, but it seemed  like the easiest way to handle #360.

### CODE REVIEW

**Comment by jakebolewski** [comment]
Isn't the space incorrect doing it this way?  I think you would have to level set the local geometry object as well and re-build a pure horizontal space, otherwise the coordinates will be incorrect.  If this is for plotting we only need the datalyout inferface.

**Comment by simonbyrne** [comment]
Yes, I need to think a bit more about how we might use this, so it should be considered experimental for now. At the moment, the main purpose is to be able to plot things.

**Comment by jakebolewski** [comment]
it's kind of weird because as soon as you take a level the global geometry changes as well, or else if the domain is not a pure 2D shell (ex with topography) you have some form of warped surface

**Comment by simonbyrne** [comment]
Yeah, this is the same problem for boundary fields (#325).

**Comment by jakebolewski** [comment]
It will come also in being able to compute derived level fields of ex. constant pressure

**Review by jakebolewski — APPROVED** [review]
LGTM (addresses by comments above), I guess i"m wondering how we will support this interface if / when we have nodal elements in the vertical?

**Comment by simonbyrne** [comment]
Use two arts `level(field, v, k)`?

**Pull request merged**
