### PR TITLE
Speed up inertial gravity wave examples (part of #1263)

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR only includes a few commits in #1263, to see where things are going wrong.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
I'm fine with merging this incrementally since this is still an improvement. I think I mixed something up in the cache in #1264, I'm fine with rebasing that once this is merged. @valeriabarra, can you please review?

**Comment by charleskawczynski** [comment]
Performance improvement in this PR:
main:
`ρfb_init | Time: 0:08:35 (515 seconds)`
This PR:
`ρfb_init_coefs!: 84.133786 seconds (4.07 M allocations: 188.954 MiB, 1.03% compilation time)`

**Comment by charleskawczynski** [comment]
A step towards #837.

**Comment by valeriabarra** [comment]
It looks good to me. However, I think the best person to review this is @dennisYatunin, as he was the author of this example. I only made a small modification later to use stretched grids.

**Pull request merged**
