### PR TITLE
Qualify IntervalSets and OrderedCollections

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR qualifies types/methods in IntervalSets and OrderedCollections.

This is a peel off of https://github.com/CliMA/ClimaCore.jl/pull/2078.

### CODE REVIEW

**Review by Sbozzolo — COMMENTED** [review]
The change for OrderedCollections is more subtle. I moved it to a different commit here: https://github.com/CliMA/ClimaCore.jl/pull/2078/commits/c35c57cce162ccca8eed26815203782c67edbb12

I have to remove OrderedCollecions because I could not find a lower version that was compatible.

**Comment by charleskawczynski** [comment]
> The change for OrderedCollections is more subtle. I moved it to a different commit here: [c35c57c](https://github.com/CliMA/ClimaCore.jl/commit/c35c57cce162ccca8eed26815203782c67edbb12)
> 
> I have to remove OrderedCollecions because I could not find a lower version that was compatible.

Hm, that's a bit odd, DataStructures just depends on OrderedCollections

**Comment by Sbozzolo** [comment]
I tried a little bit and couldn't get it to work. Given that the package is only use in tests and we already depend on DataStructures, it was simpler and quicker to just use DataStructures directly.

**Comment by charleskawczynski** [comment]
> I tried a little bit and couldn't get it to work. Given that the package is only use in tests and we already depend on DataStructures, it was simpler and quicker to just use DataStructures directly.

That's a bit unfortunate, I'd prefer we use the lower level dependencies. That said, having correctly configured lower compat bounds seems like a much bigger win to me. So I'm fine with this.

Superseded by #2078.

**Pull request closed without merging**
