### PR TITLE
cap OpenMPI_jll to v4

### PR DESCRIPTION
**Pull request by simonbyrne**
Hopefully should fix some of the errors

- [ ] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code is exercised in an integration test OR N/A.
- [ ] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by Sbozzolo** [comment]
I think we only need to do this in the `perf` environment.  For `example` we can remove the `HDF5_jll` pin.

**Comment by simonbyrne** [comment]
bors ping

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
No longer necessary as it is done in MPI.jl

**Pull request closed without merging**
