### PR TITLE
Split out plotting infa into a subpackage

### LINKED ISSUE #362: Move PlottingRecipes into its own subpackage, split out UnicodePlots
It is starting to accumulate some dependencies so probably it would be good to do this now before more are added.

### PR DESCRIPTION
**Pull request by jakebolewski**
Closes #362

### CODE REVIEW

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try-

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
I think this is finally done, people really need to qualify their imports what a mess lol.

**Comment by jakebolewski** [comment]
bors try

**Review by simonbyrne — APPROVED** [review]

**Pull request merged**
