### PR TITLE
Default solving grid stretching w Float64

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR adjusts the `GeneralizedExponentialStretching` by adding `tol` as a kwarg and allowing users to specify the float type when solving for the grid stretch parameters. This PR changes the default to `Float64`, to avoid accumulated precision errors with Float32, then type casts to `FT` on the resulting faces.

This is technically behavior changing, we could change `FT_solve = Float64` to `FT_solve = FT` to make it non-behavior changing, however, I think this is probably what users would want / expect from this function.

### CODE REVIEW

**Review by szy21 — APPROVED** [review]
Looks good to me, thanks! I don’t know why the unit tests fail though.

**Comment by charleskawczynski** [comment]
> Looks good to me, thanks! I don’t know why the unit tests fail though.

Yeah, I'm not sure it's related, though. Those same tests are failing in other PRs (e.g., #793). It very well may be from a dependency update (we don't check in the manifest for the test environment).

**Comment by charleskawczynski** [comment]
I'll let that get sorted out before merging.

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
I just revived this PR, cc @szy21!

**Review by szy21 — APPROVED** [review]
Thanks Charlie!

**Comment by charleskawczynski** [comment]
bors try

**Pull request merged**
