### PR TITLE
Conformal cubed sphere support and add warp/unwarp function tests

### PR DESCRIPTION
**Pull request by valeriabarra**
This PR adds support in ClimaCore of the Conformal cubed-sphere. This type of cubed-sphere is the one used in Oceananigans.jl, hence, adding the same type of cubed-sphere to ClimaCore will help the Coupler module with regridding on spherical domains. It also enables the possibility of using TempestRemapping one day for spherical domain regridding. 

While at it, I noticed that none of the unwarp functions and tests we used to have on cubed-sphere warp/unwarp functions were ported over to ClimaCore. Thus, I added them here. I decided to add the tests in a new test file named `test/cubed_spheres.jl` and rename the existing `test/sphere.jl` -> `test/sphere_geometry.jl`.

### CODE REVIEW

**Comment by valeriabarra** [comment]
bors try

**Comment by valeriabarra** [comment]
@simonbyrne did you have a chance to take a look at this? It ports over some functionality and tests from ClimateMachine

**Comment by valeriabarra** [comment]
@simonbyrne was the suggestion that the inverse functions are not useful anymore, or they could still be useful?

**Comment by simonbyrne** [comment]
I'd like to rethink the interface a bit here, but we can do that later.

**Comment by valeriabarra** [comment]
thanks. I can squash commits first and r+ again

**Review by simonbyrne — APPROVED** [review]

**Pull request merged**
