### PR TITLE
Enable indexing FieldVectors with column indices

### LINKED ISSUE #1442: Enable indexing FieldVectors with column indices
**Is your feature request related to a problem? Please describe.**
We need to be able to index `FieldVectors` so we can easily pass large state vectors to columnwise functions. This will avoid having to splat all fields in function arguments. 

**Describe the solution you'd like**
Extend the `Base.getindex` function

### PR DESCRIPTION
**Pull request by LenkaNovak**
Closes #1442 

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Review by akshaysridhar — APPROVED** [review]
LGTM. Thanks for adding this method.

**Comment by akshaysridhar** [comment]
bors try

**Review by charleskawczynski — COMMENTED** [review]
Can we add an inference test to this? I don't think that the FieldVector outer constructor is type stable

**Comment by LenkaNovak** [comment]
> don't think that the FieldVector outer constructor is type stable

Hi @charleskawczynski , thanks for reviewing. And sure we can add an interface test! What exactly do you have in mind? There are other functions in the same file that test methods dispatched on `FieldVector`, so I assumed it was safe.

**Comment by charleskawczynski** [comment]
> Hi @charleskawczynski , thanks for reviewing. And sure we can add an interface test! What exactly do you have in mind? There are other functions in the same file that test methods dispatched on `FieldVector`, so I assumed it was safe.

It's safe, but calling that particular outer constructor is not type-stable. Please see https://github.com/CliMA/ClimaAtmos.jl/pull/2079 for an attempted fix where we're hitting the same problem with the old TC code. It has a huge performance penalty-- note that it's completely fine to use once or twice (outside of `step!`), but (at least) the constructor that calls `promote_type(map(RecursiveArrayTools.recursive_bottom_eltype, values)...)` should really not be put inside `step!`.

**Review by charleskawczynski — APPROVED** [review]
Alright, this new version is fully inferred and only allocates 32 bytes (per column). So I think this can work.

Thanks for fixing this @LenkaNovak!

**Comment by charleskawczynski** [comment]
Actually, I'm not sure that this is working, see [this build](https://buildkite.com/clima/climaatmos-ci/builds/12802#018a76b6-9aa9-4b84-b3e7-197884051208), which fails 🤔

**Comment by LenkaNovak** [comment]
Awesome, thank you for your help, @charleskawczynski !

> Actually, I'm not sure that this is working, see [this build](https://buildkite.com/clima/climaatmos-ci/builds/12802#018a76b6-9aa9-4b84-b3e7-197884051208), which fails 🤔

Ahh, is that indexing a FieldVector of FieldVectors?

**Comment by charleskawczynski** [comment]
Actually, I think the breaking part is due to how we handled names in the old TC code. I think this should be fine, so long we add a test that `propertynames(field_vector) == propertynames(field_vector[colidx])`.

**Comment by LenkaNovak** [comment]
bors try

**Comment by LenkaNovak** [comment]
bors try

**Comment by LenkaNovak** [comment]
bors try

**Comment by LenkaNovak** [comment]
bors try

**Comment by LenkaNovak** [comment]
bors try

**Comment by LenkaNovak** [comment]
bors try

**Comment by LenkaNovak** [comment]
bors try

**Pull request merged**
