### PR TITLE
Bound NonlinearSolve.jl test compat

### PR DESCRIPTION
**Pull request by simonbyrne**
Caused blow up in compilation time https://github.com/SciML/NonlinearSolve.jl/issues/223

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]

**Comment by charleskawczynski** [comment]
Do we need to add NonLinearSolve.jl as a dependency to add the compat entry?

**Comment by simonbyrne** [comment]
> Do we need to add NonLinearSolve.jl as a dependency to add the compat entry?

Why, yes we probably do.

**Comment by simonbyrne** [comment]
Fixed upstream

**Pull request closed without merging**
