### PR TITLE
Add broken test for `pow_n` issue, fix 1126

### LINKED ISSUE #1126: Broadcasting ^2 causes allocations
## Describe the bug
While working on https://github.com/CliMA/ClimaAtmos.jl/pull/1333, it became clear that using constant exponents in broadcasting (e.g. `x.^2`) caused allocations, where `abs2.(x)` did not.

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR adds a broken test reproducing #1126, and applies a fix. Closes #1126.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Review by nefrathenrici — APPROVED** [review]
Thanks for adding the test! Does this mean [this PR](https://github.com/CliMA/ClimaAtmos.jl/pull/1819) doesn't need to change the exponent use?

**Comment by charleskawczynski** [comment]
> Does this mean https://github.com/CliMA/ClimaAtmos.jl/pull/1819 doesn't need to change the exponent if there's a new ClimaCore release?

Assuming this catches that particular case, yes.

**Pull request merged**
