### PR TITLE
add support for spatially dependent boundary conditions on GPU

### PR DESCRIPTION
**Pull request by simonbyrne**
Adapt spatially-varying boundary conditions for the GPU.

Fixes https://github.com/CliMA/ClimaAtmos.jl/issues/2192

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Review by charleskawczynski — COMMENTED** [review]
I think we need to add a cuda job to buildkite:

```yaml
      - label: "Unit: hyb ops 3d"
        key: unit_hyb_ops_3d
        command: "julia --color=yes --check-bounds=yes --project=test test/Operators/hybrid/3d.jl"
```
is the only one we have right now

**Comment by simonbyrne** [comment]
Done

**Comment by charleskawczynski** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Review by charleskawczynski — APPROVED** [review]

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Pull request merged**
