### PR TITLE
Update buildkite to 1.9

### PR DESCRIPTION
**Pull request by simonbyrne**
My fork of #1417 

- [ ] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code is exercised in an integration test OR N/A.
- [ ] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
A couple of JET failures. @charleskawczynski @dennisYatunin can you look at these?

**Comment by charleskawczynski** [comment]
> A couple of JET failures. @charleskawczynski @dennisYatunin can you look at these?

Yes, I figure we can rebase this after #1417 merges. Then, we can just convert the failing JET tests to `@test_broken` and tackle those after merging this.

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Comment by charleskawczynski** [comment]
@simonbyrne, I recently re-enabled `test-os (macos-latest)`, so feel free to just disable it (it's been disabled for a while)

**Comment by simonbyrne** [comment]
bors try

**Pull request merged**
