### PR TITLE
fix hyperdiffusion in bickley jet and add hyperdiffusion in 3d deformation flow

### LINKED ISSUE #476: Update hyperdiffusion in Bickley jet and shallow water examples?
Following from the discussion in the dycore meeting, it seems we need to change the hyperviscosity to apply to the tracer tracer proportion (theta) instead of the tracer density (rho theta).

### PR DESCRIPTION
**Pull request by szy21**
This PR fixes the problem in density for the hyperdiffusion in the bickley jet example. It also adds hyperdiffusion in the 3d deformation flow example. cc @valeriabarra 

Closes #476

### CODE REVIEW

**Comment by szy21** [comment]
bors try

**Review by jiahe23 — APPROVED** [review]
lgtm

**Comment by szy21** [comment]
bors try-

**Comment by szy21** [comment]
bors try

**Comment by szy21** [comment]
bors try

**Pull request merged**
