### PR TITLE
Add ifelse allocations broadcast test

### PR DESCRIPTION
**Pull request by nefrathenrici**
Adds a simple test to see when ifelse() allocates when broadcasted.

### CODE REVIEW

**Comment by nefrathenrici** [comment]
bors try

**Comment by charleskawczynski** [comment]
Thanks! This looks great, but I'm seeing unexpected passes. Let me make sure my env is configured correctly.

**Comment by nefrathenrici** [comment]
> Thanks! This looks great, but I'm seeing unexpected passes for all of the cases!

Maybe mine is setup wrong, it looks like it's not allocating on buildkite.

**Comment by charleskawczynski** [comment]
Make sure you try (from `ClimaCore.jl/`):

```
julia --project=test
```

```julia
julia> ]
```

```pkg
test> dev .
```
to make sure your test env is configured correctly!

**Comment by nefrathenrici** [comment]
Is it a Windows issue? I saw that the test file skips tests if on Windows. I made sure the env was setup correctly, then included the file, but then I got allocations for the exponent tests:
```
Stacktrace:
 [1] macro expansion
   @ C:\Users\nathe\AppData\Local\Programs\Julia-1.8.1\share\julia\stdlib\v1.8\Test\src\Test.jl:464 [inlined]   
 [2] macro expansion
   @ C:\Users\nathe\Clima\ClimaCore.jl\test\Fields\field.jl:108 [inlined]
 [3] macro expansion
   @ C:\Users\nathe\AppData\Local\Programs\Julia-1.8.1\share\julia\stdlib\v1.8\Test\src\Test.jl:1357 [inlined]  
 [4] top-level scope
   @ C:\Users\nathe\Clima\ClimaCore.jl\test\Fields\field.jl:103
Broadcasting with ^n: Test Failed at C:\Users\nathe\Clima\ClimaCore.jl\test\Fields\field.jl:108
  Expression: p_allocated == 0
   Evaluated: 3472 == 0
```
This is a bad sign for hunting down allocations locally, I'm not sure what to do.

**Comment by nefrathenrici** [comment]
bors try

**Comment by nefrathenrici** [comment]
bors try

**Comment by nefrathenrici** [comment]
bors try

**Comment by nefrathenrici** [comment]
bors try

**Review by charleskawczynski — APPROVED** [review]
Thanks!

**Pull request merged**
