### PR TITLE
Hoist some getproperty calls inside broadcast expr

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR should improve performance a bit via manual code hoisting, see #341.

I can confirm that this reduces the number of JET complaints.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors try

**Comment by jakebolewski** [comment]
It is annoying that we have to do this but LGTM

**Review by jakebolewski — APPROVED** [review]

**Comment by jakebolewski** [comment]
I wonder if we construct the property views directly (with Subarray) if that helps....

**Comment by charleskawczynski** [comment]
> It is annoying that we have to do this but LGTM

Yeah, at least the fix is easy, though.

> I wonder if we construct the property views directly (with Subarray bypassing all the checks) if that would help....

Maybe, I'm still looking through the JET results..

**Comment by jakebolewski** [comment]
We should just do it consistently in any case, I'll go through and make that change as it would he

**Comment by jakebolewski** [comment]
Could you try?

```diff
diff --git a/src/DataLayouts/DataLayouts.jl b/src/DataLayouts/DataLayouts.jl
index 0ddeba0..20eb00d 100644
--- a/src/DataLayouts/DataLayouts.jl
+++ b/src/DataLayouts/DataLayouts.jl
@@ -869,13 +869,16 @@ end
     data::VIFH{S, Ni, A},
     ::Val{Idx},
 ) where {S, Ni, A, Idx}
+    array = parent(data)
+    Nv = size(array, 1)
+    Nh = size(array, 4)
     SS = fieldtype(S, Idx)
     T = eltype(A)
     offset = fieldtypeoffset(T, S, Idx)
     nbytes = typesize(T, SS)
     field_byterange = (offset + 1):(offset + nbytes)
     return :(VIFH{$SS, $Ni}(
-        @inbounds view(parent(data), :, :, $field_byterange, :)
+        @inbounds SubArray(parent(data), Base.Slice(Base.OneTo($Nv)), Base.Slice(Base.OneTo($Ni)), $field_byterange, Base.Slice(Base.OneTo($Nh)))
     ))
 end
 ```

**Comment by charleskawczynski** [comment]
> Could you try? ...

I'll try this in a follow up PR, so that we know what perf changes are attributed to.

**Comment by jakebolewski** [comment]
actually with a generated function, that doesn't work if we don't have the extents in the type :-/ We could try it with the getproperty call that isn't a generated function by switching the impl.

**Comment by jakebolewski** [comment]
Releated: https://github.com/CliMA/ClimaCore.jl/issues/11#issue-860112968

**Pull request merged**
