### PR TITLE
define fill on Fields, remove TU.FieldFromNamedTuple

### PR DESCRIPTION
**Pull request by simonbyrne**
It probably makes sense to define this.

- [x] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code is exercised in an integration test OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]

**Comment by charleskawczynski** [comment]
@simonbyrne, I rebased and fixed two more failing tests, but it's now failing in the SEM operators, due to scalar indexing.

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
Good catch, we should probably define a proper `fill!`

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
bors try

**Pull request merged**
